import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer/footer";
import Navbar from "./components/navbar/navbar";
import { ThemeProvider } from "./components/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Quiz App by Mateo Mugnaini",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
